name: Run Pytest

on:
  pull_request:
    branches: ["main"]
jobs:
  ## job name
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: "postgres"

    steps:
      ## ソースコードチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v6

      ## 環境準備
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      ## Pythonを実行するためのライブラリをインストール
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        env:
          PYTHONPATH: .
        run: pytest -v

      - name: Print DB_USER
        run: echo "DB_USER ->  ${DB_USER}"
