name: Run Pytest

on:
  pull_request:
    branches: ["main"]
jobs:
  ## job name
  test:
    runs-on: ubuntu-latest

    steps:
      ## ソースコードチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v6

      ## 環境準備
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      ## Pythonを実行するためのライブラリをインストール
      - name: Install dependencies
        run: pip istall -r requirements.txt

      - name: Run pytest
        run: pytest
